#!/bin/bash
CURRENT_DIRECTORY=`pwd`
PROJECT_NAME=$1
PROJECT_DIRECTORY=$CURRENT_DIRECTORY/$PROJECT_NAME
TEMPLATE_DIRECTORY=~/bin/Templates/CMake
VCPKG_PATH=./dependencies/vcpkg

if [ $# -lt 1 ]; then
	echo "create-cmake-project <project-name> [type=OpenGL]"
	exit 1
fi
mkdir -p $PROJECT_DIRECTORY/src $PROJECT_DIRECTORY/include $PROJECT_DIRECTORY/docs $PROJECT_DIRECTORY/dependencies
echo -e "initialize-vcpkg:" >> $PROJECT_DIRECTORY/Makefile
echo -e "\t$VCPKG_PATH/bootstrap-vcpkg.sh" >> $PROJECT_DIRECTORY/Makefile
echo -e "\ninstall-package:" >> $PROJECT_DIRECTORY/Makefile
echo -e "\t$VCPKG_PATH/vcpkg install \$(package)" >> $PROJECT_DIRECTORY/Makefile
cat $TEMPLATE_DIRECTORY/gitignore > $PROJECT_DIRECTORY/.gitignore
sed "s/<PROJECT_NAME>/$PROJECT_NAME/g" $TEMPLATE_DIRECTORY/CMakeLists.txt > $PROJECT_DIRECTORY/CMakeLists.txt
sed -i "s@<VCPKG_PATH>@$VCPKG_PATH@g" $PROJECT_DIRECTORY/CMakeLists.txt
if [ $2=="type=OpenGL" ]; then
	cp $TEMPLATE_DIRECTORY/HelloWindow.cpp $PROJECT_DIRECTORY/src/main.cpp
	sed -i "s/<PROJECT_NAME>/$PROJECT_NAME/g" $PROJECT_DIRECTORY/src/main.cpp
else
	cat $TEMPLATE_DIRECTORY/HelloWorld.cpp > $PROJECT_DIRECTORY/src/main.cpp
fi	
cat $TEMPLATE_DIRECTORY/configuration.hpp.in > $PROJECT_DIRECTORY/include/configuration.hpp.in
sed "s/<PROJECT_NAME>/$PROJECT_NAME/g" $TEMPLATE_DIRECTORY/README.md > $PROJECT_DIRECTORY/README.md
touch $PROJECT_DIRECTORY/docs/index.md $PROJECT_DIRECTORY/docs/Notes.md
git init $PROJECT_DIRECTORY
cd $PROJECT_DIRECTORY
git submodule add https://github.com/microsoft/vcpkg ./dependencies/vcpkg
if [ $2=="type=OpenGL" ]; then
	make initialize-vcpkg
	make package=glfw3 install-package | tail -n3 >> .temp
	make package=glew install-package | tail -n3 >> .temp
	make package=imgui install-package | tail -n3 >> .temp
	make package=glm install-package | tail -n3 >> .temp
	sed -i "s/main/$1/g" .temp
	echo -e "\nPaste the following lines into CMakeLists.txt"
	cat .temp
	rm .temp
fi
